/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RedemptionRouteImport } from './routes/redemption'
import { Route as MintRouteImport } from './routes/mint'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as CouponRouteImport } from './routes/coupon'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as IndexRouteImport } from './routes/index'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RedemptionRoute = RedemptionRouteImport.update({
  id: '/redemption',
  path: '/redemption',
  getParentRoute: () => rootRouteImport,
} as any)
const MintRoute = MintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponRoute = CouponRouteImport.update({
  id: '/coupon',
  path: '/coupon',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/coupon': typeof CouponRoute
  '/inspector': typeof InspectorRoute
  '/mint': typeof MintRoute
  '/redemption': typeof RedemptionRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/transfer': typeof TransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/coupon': typeof CouponRoute
  '/inspector': typeof InspectorRoute
  '/mint': typeof MintRoute
  '/redemption': typeof RedemptionRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/transfer': typeof TransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/coupon': typeof CouponRoute
  '/inspector': typeof InspectorRoute
  '/mint': typeof MintRoute
  '/redemption': typeof RedemptionRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/transfer': typeof TransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/coupon'
    | '/inspector'
    | '/mint'
    | '/redemption'
    | '/settings'
    | '/setup'
    | '/terms'
    | '/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/coupon'
    | '/inspector'
    | '/mint'
    | '/redemption'
    | '/settings'
    | '/setup'
    | '/terms'
    | '/transfer'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/coupon'
    | '/inspector'
    | '/mint'
    | '/redemption'
    | '/settings'
    | '/setup'
    | '/terms'
    | '/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  CouponRoute: typeof CouponRoute
  InspectorRoute: typeof InspectorRoute
  MintRoute: typeof MintRoute
  RedemptionRoute: typeof RedemptionRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TermsRoute: typeof TermsRoute
  TransferRoute: typeof TransferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redemption': {
      id: '/redemption'
      path: '/redemption'
      fullPath: '/redemption'
      preLoaderRoute: typeof RedemptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mint': {
      id: '/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof MintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon': {
      id: '/coupon'
      path: '/coupon'
      fullPath: '/coupon'
      preLoaderRoute: typeof CouponRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  CouponRoute: CouponRoute,
  InspectorRoute: InspectorRoute,
  MintRoute: MintRoute,
  RedemptionRoute: RedemptionRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TermsRoute: TermsRoute,
  TransferRoute: TransferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
